//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCrawler {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class R {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal R() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KCrawler.R", typeof(R).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 提取总数： 的本地化字符串。
        /// </summary>
        internal static string CDetails_CrawledUrl {
            get {
                return ResourceManager.GetString("CDetails_CrawledUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行完毕 的本地化字符串。
        /// </summary>
        internal static string CDetails_Done {
            get {
                return ResourceManager.GetString("CDetails_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存到： 的本地化字符串。
        /// </summary>
        internal static string CDetails_DownloadFolder {
            get {
                return ResourceManager.GetString("CDetails_DownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入口地址： 的本地化字符串。
        /// </summary>
        internal static string CDetails_EntranceURL {
            get {
                return ResourceManager.GetString("CDetails_EntranceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 压缩文件类型个数： 的本地化字符串。
        /// </summary>
        internal static string CDetails_FileTotals {
            get {
                return ResourceManager.GetString("CDetails_FileTotals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已过滤的类型 的本地化字符串。
        /// </summary>
        internal static string CDetails_Filter {
            get {
                return ResourceManager.GetString("CDetails_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只提取内部链接 的本地化字符串。
        /// </summary>
        internal static string CDetails_IsInternal {
            get {
                return ResourceManager.GetString("CDetails_IsInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容包含关键字： 的本地化字符串。
        /// </summary>
        internal static string CDetails_Keywords {
            get {
                return ResourceManager.GetString("CDetails_Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志个数： 的本地化字符串。
        /// </summary>
        internal static string CDetails_LogCount {
            get {
                return ResourceManager.GetString("CDetails_LogCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不保存文档，只提取链接 的本地化字符串。
        /// </summary>
        internal static string CDetails_NotSave {
            get {
                return ResourceManager.GetString("CDetails_NotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提取优先级 的本地化字符串。
        /// </summary>
        internal static string CDetails_Priority {
            get {
                return ResourceManager.GetString("CDetails_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 队列个数： 的本地化字符串。
        /// </summary>
        internal static string CDetails_QueueCount {
            get {
                return ResourceManager.GetString("CDetails_QueueCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务细节 的本地化字符串。
        /// </summary>
        internal static string CDetails_TaskDetail {
            get {
                return ResourceManager.GetString("CDetails_TaskDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务编号： 的本地化字符串。
        /// </summary>
        internal static string CDetails_TaskID {
            get {
                return ResourceManager.GetString("CDetails_TaskID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务名称： 的本地化字符串。
        /// </summary>
        internal static string CDetails_TaskName {
            get {
                return ResourceManager.GetString("CDetails_TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优先级：{0} 过滤：{1} 地址关键字：{2} 内容关键字：{3} 的本地化字符串。
        /// </summary>
        internal static string CDetails_Total {
            get {
                return ResourceManager.GetString("CDetails_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编码： 的本地化字符串。
        /// </summary>
        internal static string CDetails_Unicode {
            get {
                return ResourceManager.GetString("CDetails_Unicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址包含关键字： 的本地化字符串。
        /// </summary>
        internal static string CDetails_UrlKeywords {
            get {
                return ResourceManager.GetString("CDetails_UrlKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已过滤： 的本地化字符串。
        /// </summary>
        internal static string CrawlerSets_Filter {
            get {
                return ResourceManager.GetString("CrawlerSets_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅内部链接 的本地化字符串。
        /// </summary>
        internal static string CrawlerSets_Internal {
            get {
                return ResourceManager.GetString("CrawlerSets_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关键字： 的本地化字符串。
        /// </summary>
        internal static string CrawlerSets_Keywords {
            get {
                return ResourceManager.GetString("CrawlerSets_Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不保存文件 的本地化字符串。
        /// </summary>
        internal static string CrawlerSets_NotSave {
            get {
                return ResourceManager.GetString("CrawlerSets_NotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优先级： 的本地化字符串。
        /// </summary>
        internal static string CrawlerSets_Priority {
            get {
                return ResourceManager.GetString("CrawlerSets_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址关键字： 的本地化字符串。
        /// </summary>
        internal static string CrawlerSets_UrlKeywords {
            get {
                return ResourceManager.GetString("CrawlerSets_UrlKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取中 的本地化字符串。
        /// </summary>
        internal static string CrawlerStatusType_Fetch {
            get {
                return ResourceManager.GetString("CrawlerStatusType_Fetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理中 的本地化字符串。
        /// </summary>
        internal static string CrawlerStatusType_Parse {
            get {
                return ResourceManager.GetString("CrawlerStatusType_Parse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存中 的本地化字符串。
        /// </summary>
        internal static string CrawlerStatusType_Save {
            get {
                return ResourceManager.GetString("CrawlerStatusType_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待中 的本地化字符串。
        /// </summary>
        internal static string CrawlerStatusType_Sleep {
            get {
                return ResourceManager.GetString("CrawlerStatusType_Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停 的本地化字符串。
        /// </summary>
        internal static string DownloaderStatus_Pause {
            get {
                return ResourceManager.GetString("DownloaderStatus_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行 的本地化字符串。
        /// </summary>
        internal static string DownloaderStatus_Running {
            get {
                return ResourceManager.GetString("DownloaderStatus_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        internal static string DownloaderStatus_Stopped {
            get {
                return ResourceManager.GetString("DownloaderStatus_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容 的本地化字符串。
        /// </summary>
        internal static string Extract_Content {
            get {
                return ResourceManager.GetString("Extract_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接 的本地化字符串。
        /// </summary>
        internal static string Extract_Links {
            get {
                return ResourceManager.GetString("Extract_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正则 的本地化字符串。
        /// </summary>
        internal static string Extract_Split_RegEx {
            get {
                return ResourceManager.GetString("Extract_Split_RegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前后 的本地化字符串。
        /// </summary>
        internal static string Extract_Split_StartLast {
            get {
                return ResourceManager.GetString("Extract_Split_StartLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 低级： 的本地化字符串。
        /// </summary>
        internal static string Level_1 {
            get {
                return ResourceManager.GetString("Level_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中低级： 的本地化字符串。
        /// </summary>
        internal static string Level_2 {
            get {
                return ResourceManager.GetString("Level_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中级： 的本地化字符串。
        /// </summary>
        internal static string Level_3 {
            get {
                return ResourceManager.GetString("Level_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中高级： 的本地化字符串。
        /// </summary>
        internal static string Level_4 {
            get {
                return ResourceManager.GetString("Level_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最高级： 的本地化字符串。
        /// </summary>
        internal static string Level_5 {
            get {
                return ResourceManager.GetString("Level_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另一个程序正在使用此文件，进程无法访问。 的本地化字符串。
        /// </summary>
        internal static string Log_Error_FileInProgress {
            get {
                return ResourceManager.GetString("Log_Error_FileInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件不存在 的本地化字符串。
        /// </summary>
        internal static string Log_Error_NotExist {
            get {
                return ResourceManager.GetString("Log_Error_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 远程主机强迫关闭了一个现有的连接 的本地化字符串。
        /// </summary>
        internal static string Log_Error_SocketException {
            get {
                return ResourceManager.GetString("Log_Error_SocketException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在存储队列 的本地化字符串。
        /// </summary>
        internal static string Log_Info_SavingQueue {
            get {
                return ResourceManager.GetString("Log_Info_SavingQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在存储唯一URL 的本地化字符串。
        /// </summary>
        internal static string Log_Info_SavingUrl {
            get {
                return ResourceManager.GetString("Log_Info_SavingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认设置（请到优先级选项卡自行设置） 的本地化字符串。
        /// </summary>
        internal static string MCate_Default {
            get {
                return ResourceManager.GetString("MCate_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统自动生成关键字名称: 的本地化字符串。
        /// </summary>
        internal static string MCate_LabelPrefix {
            get {
                return ResourceManager.GetString("MCate_LabelPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件大小： 的本地化字符串。
        /// </summary>
        internal static string Range_FileSize {
            get {
                return ResourceManager.GetString("Range_FileSize", resourceCulture);
            }
        }
    }
}
