//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netscape {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class R {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal R() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Netscape.R", typeof(R).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 请选择下载保存文件夹路径 的本地化字符串。
        /// </summary>
        internal static string ACrawer_EmptyDownloadFolder {
            get {
                return ResourceManager.GetString("ACrawer_EmptyDownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建 的本地化字符串。
        /// </summary>
        internal static string ACrawer_NewTaskTitle {
            get {
                return ResourceManager.GetString("ACrawer_NewTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存路径，不填写则默认保存到： 的本地化字符串。
        /// </summary>
        internal static string ACrawler_DownloadFolderInfo {
            get {
                return ResourceManager.GetString("ACrawler_DownloadFolderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务添加完毕是否要配置其他项目（如优先级、过滤器等）？ 的本地化字符串。
        /// </summary>
        internal static string ACrawler_NewlyAddedInfo {
            get {
                return ResourceManager.GetString("ACrawler_NewlyAddedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提取总数： 的本地化字符串。
        /// </summary>
        internal static string CDetails_CrawledUrl {
            get {
                return ResourceManager.GetString("CDetails_CrawledUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行完毕 的本地化字符串。
        /// </summary>
        internal static string CDetails_Done {
            get {
                return ResourceManager.GetString("CDetails_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存到： 的本地化字符串。
        /// </summary>
        internal static string CDetails_DownloadFolder {
            get {
                return ResourceManager.GetString("CDetails_DownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入口地址： 的本地化字符串。
        /// </summary>
        internal static string CDetails_EntranceURL {
            get {
                return ResourceManager.GetString("CDetails_EntranceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 压缩文件类型个数： 的本地化字符串。
        /// </summary>
        internal static string CDetails_FileTotals {
            get {
                return ResourceManager.GetString("CDetails_FileTotals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已过滤的类型 的本地化字符串。
        /// </summary>
        internal static string CDetails_Filter {
            get {
                return ResourceManager.GetString("CDetails_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只提取内部链接 的本地化字符串。
        /// </summary>
        internal static string CDetails_IsInternal {
            get {
                return ResourceManager.GetString("CDetails_IsInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容包含关键字 的本地化字符串。
        /// </summary>
        internal static string CDetails_Keywords {
            get {
                return ResourceManager.GetString("CDetails_Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志个数： 的本地化字符串。
        /// </summary>
        internal static string CDetails_LogCount {
            get {
                return ResourceManager.GetString("CDetails_LogCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不保存文档，只提取链接 的本地化字符串。
        /// </summary>
        internal static string CDetails_NotSave {
            get {
                return ResourceManager.GetString("CDetails_NotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提取优先级 的本地化字符串。
        /// </summary>
        internal static string CDetails_Priority {
            get {
                return ResourceManager.GetString("CDetails_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 队列个数： 的本地化字符串。
        /// </summary>
        internal static string CDetails_QueueCount {
            get {
                return ResourceManager.GetString("CDetails_QueueCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务细节 的本地化字符串。
        /// </summary>
        internal static string CDetails_TaskDetail {
            get {
                return ResourceManager.GetString("CDetails_TaskDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务编号： 的本地化字符串。
        /// </summary>
        internal static string CDetails_TaskID {
            get {
                return ResourceManager.GetString("CDetails_TaskID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务名称： 的本地化字符串。
        /// </summary>
        internal static string CDetails_TaskName {
            get {
                return ResourceManager.GetString("CDetails_TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优先级：{0} 过滤：{1} 地址关键字：{2} 内容关键字：{3} 的本地化字符串。
        /// </summary>
        internal static string CDetails_Total {
            get {
                return ResourceManager.GetString("CDetails_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编码： 的本地化字符串。
        /// </summary>
        internal static string CDetails_Unicode {
            get {
                return ResourceManager.GetString("CDetails_Unicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址包含关键字： 的本地化字符串。
        /// </summary>
        internal static string CDetails_UrlKeywords {
            get {
                return ResourceManager.GetString("CDetails_UrlKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已过滤： 的本地化字符串。
        /// </summary>
        internal static string CrawlerSets_Filter {
            get {
                return ResourceManager.GetString("CrawlerSets_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关键字： 的本地化字符串。
        /// </summary>
        internal static string CrawlerSets_Keywords {
            get {
                return ResourceManager.GetString("CrawlerSets_Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优先级： 的本地化字符串。
        /// </summary>
        internal static string CrawlerSets_Priority {
            get {
                return ResourceManager.GetString("CrawlerSets_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址关键字： 的本地化字符串。
        /// </summary>
        internal static string CrawlerSets_UrlKeywords {
            get {
                return ResourceManager.GetString("CrawlerSets_UrlKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取中 的本地化字符串。
        /// </summary>
        internal static string CrawlerStatusType_Fetch {
            get {
                return ResourceManager.GetString("CrawlerStatusType_Fetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理中 的本地化字符串。
        /// </summary>
        internal static string CrawlerStatusType_Parse {
            get {
                return ResourceManager.GetString("CrawlerStatusType_Parse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存中 的本地化字符串。
        /// </summary>
        internal static string CrawlerStatusType_Save {
            get {
                return ResourceManager.GetString("CrawlerStatusType_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待中 的本地化字符串。
        /// </summary>
        internal static string CrawlerStatusType_Sleep {
            get {
                return ResourceManager.GetString("CrawlerStatusType_Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string CTasK_AreOnlyLinks {
            get {
                return ResourceManager.GetString("CTasK_AreOnlyLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除记录后则重新抓取，确定要清除： 的本地化字符串。
        /// </summary>
        internal static string CTask_ClearTask {
            get {
                return ResourceManager.GetString("CTask_ClearTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否要删除任务（下载文件不会清除）？ 的本地化字符串。
        /// </summary>
        internal static string CTask_ConfirmRemoveTask {
            get {
                return ResourceManager.GetString("CTask_ConfirmRemoveTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出完毕、是否打开下载目录？ 的本地化字符串。
        /// </summary>
        internal static string CTask_ExportedInfo {
            get {
                return ResourceManager.GetString("CTask_ExportedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string CTasK_IsInternal {
            get {
                return ResourceManager.GetString("CTasK_IsInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一个任务 的本地化字符串。
        /// </summary>
        internal static string CTask_NullTaskSelected {
            get {
                return ResourceManager.GetString("CTask_NullTaskSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在启动任务请稍后...... 的本地化字符串。
        /// </summary>
        internal static string CTask_StartingTask {
            get {
                return ResourceManager.GetString("CTask_StartingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停 的本地化字符串。
        /// </summary>
        internal static string DownloaderStatus_Pause {
            get {
                return ResourceManager.GetString("DownloaderStatus_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行 的本地化字符串。
        /// </summary>
        internal static string DownloaderStatus_Running {
            get {
                return ResourceManager.GetString("DownloaderStatus_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        internal static string DownloaderStatus_Stopped {
            get {
                return ResourceManager.GetString("DownloaderStatus_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出日志 的本地化字符串。
        /// </summary>
        internal static string Dump_Type_Export {
            get {
                return ResourceManager.GetString("Dump_Type_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入任务名称 的本地化字符串。
        /// </summary>
        internal static string Empty_TaskName {
            get {
                return ResourceManager.GetString("Empty_TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请提供入口URL地址,例如(http://www.google.com) 的本地化字符串。
        /// </summary>
        internal static string Empty_Url {
            get {
                return ResourceManager.GetString("Empty_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入相应信息 的本地化字符串。
        /// </summary>
        internal static string EmptyInfo {
            get {
                return ResourceManager.GetString("EmptyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入要获取资源的网址 的本地化字符串。
        /// </summary>
        internal static string Error_WrongUrl {
            get {
                return ResourceManager.GetString("Error_WrongUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出窗口时间间隔({0}毫秒): 的本地化字符串。
        /// </summary>
        internal static string KGen_Interval {
            get {
                return ResourceManager.GetString("KGen_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在结束任务请稍后...... 的本地化字符串。
        /// </summary>
        internal static string KMain_Aborting {
            get {
                return ResourceManager.GetString("KMain_Aborting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎您使用金蜘蛛 任务总数： 的本地化字符串。
        /// </summary>
        internal static string KMain_BallonWelcome {
            get {
                return ResourceManager.GetString("KMain_BallonWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有任务已经启动 的本地化字符串。
        /// </summary>
        internal static string KMain_Lunch {
            get {
                return ResourceManager.GetString("KMain_Lunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有任务已经暂停 的本地化字符串。
        /// </summary>
        internal static string KMain_Pause {
            get {
                return ResourceManager.GetString("KMain_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行中，请稍后...... 的本地化字符串。
        /// </summary>
        internal static string KMain_Progressing {
            get {
                return ResourceManager.GetString("KMain_Progressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有任务已经停止 的本地化字符串。
        /// </summary>
        internal static string KMain_Stop {
            get {
                return ResourceManager.GetString("KMain_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入关键字 的本地化字符串。
        /// </summary>
        internal static string UcKey_EmptyKeyword {
            get {
                return ResourceManager.GetString("UcKey_EmptyKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入关键字标识名称 的本地化字符串。
        /// </summary>
        internal static string UcKey_EmptyName {
            get {
                return ResourceManager.GetString("UcKey_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在获取中，请稍候………… 的本地化字符串。
        /// </summary>
        internal static string URL_Requesting {
            get {
                return ResourceManager.GetString("URL_Requesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 help.htm 的本地化字符串。
        /// </summary>
        internal static string URLHelpPage {
            get {
                return ResourceManager.GetString("URLHelpPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start.htm 的本地化字符串。
        /// </summary>
        internal static string URLStartPage {
            get {
                return ResourceManager.GetString("URLStartPage", resourceCulture);
            }
        }
    }
}
